# Minimal configuration for production
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'fr'
    
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
        
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'

twig:
    default_path: '%kernel.project_dir%/templates'
